---
type: yml
auth:
  sign_key: secret

mysql:
  port: 3306
  host: localhost
  db_name: gameapp_db
  username: root
  password: password

http_server:
  port: 7777

redis:
  port: 6379
  host: localhost
  db: 0
  password: ""

matching_service:
  waiting_timeout: "2m"

presence_service:
  expiration_time: "60m"
  prefix: "presence"