version: '3.7'

services:
  gameapp-database:
    image: 'mysql/mysql-server:8.0'
    ports:
      - "3306:3306"
    container_name: gameapp-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  gameapp-redis:
    image: redis:alpine
    container_name: gameapp-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --protected-mode no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - gameapp-redis-data:/data

volumes:
  dbdata:
  gameapp-redis-data: