version: '3.7'

services:
  gameapp-database:
    image: 'mysql/mysql-server:8.0'
    ports:
      - "3306:3306"
    container_name: gameapp-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  gameapp-redis:
    image: redis:alpine
    container_name: gameapp-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --protected-mode no --save "" --appendonly no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - gameapp-redis-data:/data
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: [ "nats" ]
  nats-1:
      image: nats
      command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
      networks: [ "nats" ]
      depends_on: [ "nats" ]

volumes:
  dbdata:
  gameapp-redis-data:
networks:
  nats:
    name: nats